version: "3.8"

services:
  server:
    build:
       context: .
       dockerfile: Dockerfile
    ports:
      - 3001:3000
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'nodejs_api'
      MYSQL_USER: 'alfa'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password123'
    volumes:
      - $PWD:/docker-entrypoint-initdb.d

